apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-leader-redis
  namespace: guestbook
  labels:
    team: teamName
    prometheus: "yes"
spec:
  selector:
    matchLabels:
      app: redis-leader
  endpoints:
  - port: metrics


